export const CONSTANTS = {
    ADD_CONTACT: 'ADD CONTACT',
    EDIT_CONTACT: 'EDIT CONTACT',
    SAVE_CONTACT: 'SAVE CONTACT',
    SAVE_CHANGES: 'SAVE CHANGES',
    ADD_NEW_CONTACT: 'ADD NEW CONTACT',
};
